spring.application.name=todoApp

# バナーを非表示にする
spring.main.banner-mode=off

#
# JDBC Properties
#
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=springstudent
spring.datasource.password=springstudent

#
# Log JDBC SQL Statements
#
# Only use this for dev/testing
# DO NOT use in production
Logging.level.org.springframework.jdbc.core = TRACE

