spring.application.name=todoApp


# Turn off the banner
spring.main.banner-mode=off


#
#
#
countries=France,Germany,India,Brazil,Mexico,Spain,United States,Japan
languages=Java,Python,JavaScript,TypeScript
