spring.application.name=todoApp
management.endpoints.web.exposure.include=health,info
# management.endpoints.web.exposure.include=*
management.info.env.enabled=true

# management.endpoints.web.exposure.exclude==health,info

info.app.version=1.0.0
info.app.description=This is a simple Todo application backend.
info.app.name=Todo Application

# define my custom property
coach.name=John Doe
team.name=Development Team

#
# Change Spring Boot embedded server port
#
server.port=7070

#
# Set the context path for the application
#
server.servlet.context-path=/todoapp
